# Generated by Django 4.1.4 on 2023-01-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail',
            new_name='thumbnails',
        ),
    ]
