# Generated by Django 4.1.4 on 2023-01-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_rename_thumbnail_course_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnails',
        ),
    ]
