# Generated by Django 4.1.4 on 2023-01-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_course_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnails',
            field=models.ImageField(default='https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220401124017/HTML-Tutorial.png', upload_to='image/'),
        ),
    ]
