# Generated by Django 4.1.4 on 2022-12-31 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Video_approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.video')),
            ],
        ),
    ]
