# Generated by Django 4.1.4 on 2023-01-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_video_active_video_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_approve',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.video', unique=True),
        ),
    ]
