# Generated by Django 4.1.4 on 2023-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_alter_video_approve_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_approve',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
