# Generated by Django 4.1.4 on 2023-01-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_course_category'),
        ('analytics', '0002_alter_views_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to='tutor.video'),
        ),
    ]
