# Generated by Django 4.1.4 on 2023-01-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_like_video_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
