# Generated by Django 4.1.4 on 2023-01-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_dislike_like_remove_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='user',
        ),
        migrations.AlterField(
            model_name='views',
            name='view',
            field=models.IntegerField(default=1),
        ),
    ]
