# Generated by Django 4.1.4 on 2023-01-14 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_views_user_alter_views_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 14, 14, 43, 6, 86308)),
        ),
    ]
